/*
File:   resources_zip.h
Author: WARNING: This file is generated by pack_resources.py! Any hand edits will be lost!
*/

#ifndef _RESOURCES_ZIP_H
#define _RESOURCES_ZIP_H

extern u8 resources_zip_bytes[312679];

#endif //_RESOURCES_ZIP_H

